---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: multi-file-process-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/shgovind/kind-pvc/multi  # Use the same path as in your kind config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multi-file-process-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard